package cine;

public enum Genero {
	ACCION, ANIMACION, AVENTURAS, BELICO, CIENCIAFICCION, CINENEGRO, COMEDIA, DOCUMENTAL, DRAMA, FANTASTICO, INFANTIL, INTRIGA, MUSICAL, ROMANTICA, TERROR, THRILLER, WESTERN;
}
